//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabbyCat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabbyCat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap action_add_16xLG {
            get {
                object obj = ResourceManager.GetObject("action_add_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackHS {
            get {
                object obj = ResourceManager.GetObject("BackHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The built-in vertex shader variables are intrinsically declared as follows:
        ///
        ///in int gl_VertexID;      // only present when not targeting Vulkan
        ///in int gl_InstanceID;    // only present when not targeting Vulkan
        ///in int gl_VertexIndex;   // only present when targeting Vulkan
        ///in int gl_InstanceIndex; // only present when targeting Vulkan
        ///in int gl_DrawID;
        ///in int gl_BaseVertex;
        ///in int gl_BaseInstance;
        ///
        ///out gl_PerVertex {
        ///  vec4 gl_Position;
        ///  float gl_PointSize;
        ///  float gl_ClipDistance[];
        ///  float  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Built_in_Shader1Vertex {
            get {
                return ResourceManager.GetString("Built_in_Shader1Vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the tessellation control shader, built-in variables are intrinsically declared as:
        ///
        ///in gl_PerVertex {
        ///    vec4 gl_Position;
        ///    float gl_PointSize;
        ///    float gl_ClipDistance[];
        ///    float gl_CullDistance[];
        ///} gl_in[gl_MaxPatchVertices];
        ///
        ///in int gl_PatchVerticesIn;
        ///in int gl_PrimitiveID;
        ///in int gl_InvocationID;
        ///
        ///out gl_PerVertex {
        ///    vec4 gl_Position;
        ///    float gl_PointSize;
        ///    float gl_ClipDistance[];
        ///    float gl_CullDistance[];
        ///} gl_out[];
        ///
        ///patch out float gl_TessLevelOuter[4];
        ///pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Built_in_Shader2TessControl {
            get {
                return ResourceManager.GetString("Built_in_Shader2TessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the tessellation evaluation shader, built-in variables are intrinsically declared as:
        ///
        ///in gl_PerVertex {
        ///    vec4 gl_Position;
        ///    float gl_PointSize;
        ///    float gl_ClipDistance[];
        ///    float gl_CullDistance[];
        ///} gl_in[gl_MaxPatchVertices];
        ///
        ///in int gl_PatchVerticesIn;
        ///in int gl_PrimitiveID;
        ///in vec3 gl_TessCoord;
        ///patch in float gl_TessLevelOuter[4];
        ///patch in float gl_TessLevelInner[2];
        ///
        ///out gl_PerVertex {
        ///    vec4 gl_Position;
        ///    float gl_PointSize;
        ///    float gl_ClipDistance[];
        ///    float [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Built_in_Shader3TessEvaluation {
            get {
                return ResourceManager.GetString("Built_in_Shader3TessEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the geometry shader, built-in variables are intrinsically declared as:
        ///
        ///in gl_PerVertex {
        ///    vec4 gl_Position;
        ///    float gl_PointSize;
        ///    float gl_ClipDistance[];
        ///    float gl_CullDistance[];
        ///} gl_in[];
        ///
        ///in int gl_PrimitiveIDIn;
        ///in int gl_InvocationID;
        ///
        ///out gl_PerVertex {
        ///    vec4 gl_Position;
        ///    float gl_PointSize;
        ///    float gl_ClipDistance[];
        ///    float gl_CullDistance[];
        ///};
        ///
        ///out int gl_PrimitiveID;
        ///out int gl_Layer;
        ///out int gl_ViewportIndex;
        ///
        ///Geometry Shader Input Variables
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Built_in_Shader4Geometry {
            get {
                return ResourceManager.GetString("Built_in_Shader4Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The built-in special variables that are accessible from a 
        ///fragment shader are intrinsically declared as follows:
        ///
        ///in vec4 gl_FragCoord;
        ///in bool gl_FrontFacing;
        ///in float gl_ClipDistance[];
        ///in float gl_CullDistance[];
        ///in vec2 gl_PointCoord;
        ///in int gl_PrimitiveID;
        ///in int gl_SampleID;
        ///in vec2 gl_SamplePosition;
        ///in int gl_SampleMaskIn[];
        ///in int gl_Layer;
        ///in int gl_ViewportIndex;
        ///in bool gl_HelperInvocation;
        ///
        ///out float gl_FragDepth;
        ///out int gl_SampleMask[];
        ///
        ///The output of the fragment shader e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Built_in_Shader5Fragment {
            get {
                return ResourceManager.GetString("Built_in_Shader5Fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the compute shader, built-in variables are declared as follows:
        ///
        ///// workgroup dimensions
        ///in uvec3 gl_NumWorkGroups;
        ///const uvec3 gl_WorkGroupSize;
        ///
        ///// workgroup and invocation IDs
        ///in uvec3 gl_WorkGroupID;
        ///in uvec3 gl_LocalInvocationID;
        ///
        ///// derived variables
        ///in uvec3 gl_GlobalInvocationID;
        ///in uint gl_LocalInvocationIndex;
        ///
        ///The built-in variable gl_NumWorkGroups is a compute-shader input variable containing the number of workgroups in each dimension of the dispatch that will execute the comput [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Built_in_Shader6Compute {
            get {
                return ResourceManager.GetString("Built_in_Shader6Compute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X component of camera focus.
        /// </summary>
        internal static string Camera_FocusX {
            get {
                return ResourceManager.GetString("Camera_FocusX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y component of camera focus.
        /// </summary>
        internal static string Camera_FocusY {
            get {
                return ResourceManager.GetString("Camera_FocusY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Z component of camera focus.
        /// </summary>
        internal static string Camera_FocusZ {
            get {
                return ResourceManager.GetString("Camera_FocusZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X component of camera position.
        /// </summary>
        internal static string Camera_PositionX {
            get {
                return ResourceManager.GetString("Camera_PositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y component of camera position.
        /// </summary>
        internal static string Camera_PositionY {
            get {
                return ResourceManager.GetString("Camera_PositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Z component of camera position.
        /// </summary>
        internal static string Camera_PositionZ {
            get {
                return ResourceManager.GetString("Camera_PositionZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Color_fontHS {
            get {
                object obj = ResourceManager.GetObject("Color_fontHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorHS {
            get {
                object obj = ResourceManager.GetObject("ColorHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CopyHS {
            get {
                object obj = ResourceManager.GetObject("CopyHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CutHS {
            get {
                object obj = ResourceManager.GetObject("CutHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveFirstHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveFirstHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveLastHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveLastHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveNextHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MovePreviousHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MovePreviousHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoubleLeftArrowHS {
            get {
                object obj = ResourceManager.GetObject("DoubleLeftArrowHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoubleRightArrowHS {
            get {
                object obj = ResourceManager.GetObject("DoubleRightArrowHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_RedoHS {
            get {
                object obj = ResourceManager.GetObject("Edit_RedoHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_UndoHS {
            get {
                object obj = ResourceManager.GetObject("Edit_UndoHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditInformationHS {
            get {
                object obj = ResourceManager.GetObject("EditInformationHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditTableHS {
            get {
                object obj = ResourceManager.GetObject("EditTableHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eps_closedHS {
            get {
                object obj = ResourceManager.GetObject("eps_closedHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eps_open_largeHS {
            get {
                object obj = ResourceManager.GetObject("eps_open_largeHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eps_openHS {
            get {
                object obj = ResourceManager.GetObject("eps_openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FFwdHS {
            get {
                object obj = ResourceManager.GetObject("FFwdHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindHS {
            get {
                object obj = ResourceManager.GetObject("FindHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindNextHS {
            get {
                object obj = ResourceManager.GetObject("FindNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FlipHorizontalHS {
            get {
                object obj = ResourceManager.GetObject("FlipHorizontalHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FlipVerticalHS {
            get {
                object obj = ResourceManager.GetObject("FlipVerticalHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderHS {
            get {
                object obj = ResourceManager.GetObject("FolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FontDialogHS {
            get {
                object obj = ResourceManager.GetObject("FontDialogHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     case {0}:
        ///      execTrace{0}();
        ///      break;
        ///.
        /// </summary>
        internal static string Format_Case {
            get {
                return ResourceManager.GetString("Format_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version {0}
        ///
        ///{1}
        ///
        ///{2}void main()
        ///{{
        ///  switch (traceNumber)
        ///  {{
        ///{3}    default:
        ///      break;
        ///  }}
        ///}}.
        /// </summary>
        internal static string Format_Scene {
            get {
                return ResourceManager.GetString("Format_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void execTrace{0}() // {1}
        ///{{
        ///{2}
        ///}}
        ///
        ///.
        /// </summary>
        internal static string Format_Trace {
            get {
                return ResourceManager.GetString("Format_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FormRunHS {
            get {
                object obj = ResourceManager.GetObject("FormRunHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FullScreenHS {
            get {
                object obj = ResourceManager.GetObject("FullScreenHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FunctionHS {
            get {
                object obj = ResourceManager.GetObject("FunctionHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shader Language version targeted by this code.
        /// </summary>
        internal static string GLSL_TargetVersion {
            get {
                return ResourceManager.GetString("GLSL_TargetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoLtrHS {
            get {
                object obj = ResourceManager.GetObject("GoLtrHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoRtlHS {
            get {
                object obj = ResourceManager.GetObject("GoRtlHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoToNextHS {
            get {
                object obj = ResourceManager.GetObject("GoToNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graphhs {
            get {
                object obj = ResourceManager.GetObject("graphhs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeHS {
            get {
                object obj = ResourceManager.GetObject("HomeHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InsertHyperlinkHS {
            get {
                object obj = ResourceManager.GetObject("InsertHyperlinkHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LegendHS {
            get {
                object obj = ResourceManager.GetObject("LegendHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LineColorHS {
            get {
                object obj = ResourceManager.GetObject("LineColorHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewDocumentHS {
            get {
                object obj = ResourceManager.GetObject("NewDocumentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoteHS {
            get {
                object obj = ResourceManager.GetObject("NoteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFileHS {
            get {
                object obj = ResourceManager.GetObject("OpenFileHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openfolderHS {
            get {
                object obj = ResourceManager.GetObject("openfolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OptionsHS {
            get {
                object obj = ResourceManager.GetObject("OptionsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PasteHS {
            get {
                object obj = ResourceManager.GetObject("PasteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseHS {
            get {
                object obj = ResourceManager.GetObject("PauseHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseRecorderHS {
            get {
                object obj = ResourceManager.GetObject("PauseRecorderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PieChart3DHS {
            get {
                object obj = ResourceManager.GetObject("PieChart3DHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PieChartHS {
            get {
                object obj = ResourceManager.GetObject("PieChartHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayHS {
            get {
                object obj = ResourceManager.GetObject("PlayHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointerHS {
            get {
                object obj = ResourceManager.GetObject("PointerHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrimaryKeyHS {
            get {
                object obj = ResourceManager.GetObject("PrimaryKeyHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrintHS {
            get {
                object obj = ResourceManager.GetObject("PrintHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrintPreviewHS {
            get {
                object obj = ResourceManager.GetObject("PrintPreviewHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X component of the projection far plane.
        /// </summary>
        internal static string Projection_FarPlaneX {
            get {
                return ResourceManager.GetString("Projection_FarPlaneX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y component of the projection far plane.
        /// </summary>
        internal static string Projection_FarPlaneY {
            get {
                return ResourceManager.GetString("Projection_FarPlaneY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Z component of the projection far plane.
        /// </summary>
        internal static string Projection_FarPlaneZ {
            get {
                return ResourceManager.GetString("Projection_FarPlaneZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The perspective field of view angle (degrees).
        /// </summary>
        internal static string Projection_FieldOfView {
            get {
                return ResourceManager.GetString("Projection_FieldOfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X component of the projection near plane.
        /// </summary>
        internal static string Projection_NearPlaneX {
            get {
                return ResourceManager.GetString("Projection_NearPlaneX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y component of the projection near plane.
        /// </summary>
        internal static string Projection_NearPlaneY {
            get {
                return ResourceManager.GetString("Projection_NearPlaneY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Z component of the projection near plane.
        /// </summary>
        internal static string Projection_NearPlaneZ {
            get {
                return ResourceManager.GetString("Projection_NearPlaneZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene projection type.
        /// </summary>
        internal static string Projection_Type {
            get {
                return ResourceManager.GetString("Projection_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RepeatHS {
            get {
                object obj = ResourceManager.GetObject("RepeatHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResizeHS {
            get {
                object obj = ResourceManager.GetObject("ResizeHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RestartHS {
            get {
                object obj = ResourceManager.GetObject("RestartHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RewindHS {
            get {
                object obj = ResourceManager.GetObject("RewindHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrow2HS {
            get {
                object obj = ResourceManager.GetObject("RightArrow2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrowHS {
            get {
                object obj = ResourceManager.GetObject("RightArrowHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightToLeftDoucmentHS {
            get {
                object obj = ResourceManager.GetObject("RightToLeftDoucmentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RoutingSlipHS {
            get {
                object obj = ResourceManager.GetObject("RoutingSlipHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAllHS {
            get {
                object obj = ResourceManager.GetObject("SaveAllHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAsWebPageHS {
            get {
                object obj = ResourceManager.GetObject("SaveAsWebPageHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveFormDesignHS {
            get {
                object obj = ResourceManager.GetObject("SaveFormDesignHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The colour of the background.
        /// </summary>
        internal static string Scene_Background {
            get {
                return ResourceManager.GetString("Scene_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target number of frames per second.
        /// </summary>
        internal static string Scene_FPS {
            get {
                return ResourceManager.GetString("Scene_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of samples interpolated over.
        /// </summary>
        internal static string Scene_Samples {
            get {
                return ResourceManager.GetString("Scene_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layout (location = 0) in vec3 position;
        ///out vec3 colour;
        ///
        ///uniform float timeValue;
        ///uniform int traceNumber;
        ///uniform mat4
        ///  transform,
        ///  cameraView,
        ///  projection;.
        /// </summary>
        internal static string Scene_Shader1Vertex {
            get {
                return ResourceManager.GetString("Scene_Shader1Vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Scene_Shader2TessControl {
            get {
                return ResourceManager.GetString("Scene_Shader2TessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Scene_Shader3TessEvaluation {
            get {
                return ResourceManager.GetString("Scene_Shader3TessEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Scene_Shader4Geometry {
            get {
                return ResourceManager.GetString("Scene_Shader4Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in vec3 colour;
        ///out vec4 FragColor;
        ///
        ///uniform float timeValue;
        ///uniform int traceNumber;.
        /// </summary>
        internal static string Scene_Shader5Fragment {
            get {
                return ResourceManager.GetString("Scene_Shader5Fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Scene_Shader6Compute {
            get {
                return ResourceManager.GetString("Scene_Shader6Compute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of this scene.
        /// </summary>
        internal static string Scene_Title {
            get {
                return ResourceManager.GetString("Scene_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not to apply vertical sync.
        /// </summary>
        internal static string Scene_VSync {
            get {
                return ResourceManager.GetString("Scene_VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchWebHS {
            get {
                object obj = ResourceManager.GetObject("SearchWebHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SendBackwardHS {
            get {
                object obj = ResourceManager.GetObject("SendBackwardHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SendToBackHS {
            get {
                object obj = ResourceManager.GetObject("SendToBackHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowAllCommentsHS {
            get {
                object obj = ResourceManager.GetObject("ShowAllCommentsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowGridlines2HS {
            get {
                object obj = ResourceManager.GetObject("ShowGridlines2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowGridlinesHS {
            get {
                object obj = ResourceManager.GetObject("ShowGridlinesHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpeechMicHS {
            get {
                object obj = ResourceManager.GetObject("SpeechMicHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StopHS {
            get {
                object obj = ResourceManager.GetObject("StopHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SychronizeListHS {
            get {
                object obj = ResourceManager.GetObject("SychronizeListHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TableHS {
            get {
                object obj = ResourceManager.GetObject("TableHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TaskHS {
            get {
                object obj = ResourceManager.GetObject("TaskHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextboxHS {
            get {
                object obj = ResourceManager.GetObject("TextboxHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TileWindowsHorizontallyHS {
            get {
                object obj = ResourceManager.GetObject("TileWindowsHorizontallyHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of this trace.
        /// </summary>
        internal static string Trace_Description {
            get {
                return ResourceManager.GetString("Trace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X component of location.
        /// </summary>
        internal static string Trace_LocationX {
            get {
                return ResourceManager.GetString("Trace_LocationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y component of location.
        /// </summary>
        internal static string Trace_LocationY {
            get {
                return ResourceManager.GetString("Trace_LocationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Z component of location.
        /// </summary>
        internal static string Trace_LocationZ {
            get {
                return ResourceManager.GetString("Trace_LocationZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value of X.
        /// </summary>
        internal static string Trace_MaximumX {
            get {
                return ResourceManager.GetString("Trace_MaximumX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value of Y.
        /// </summary>
        internal static string Trace_MaximumY {
            get {
                return ResourceManager.GetString("Trace_MaximumY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value of Z.
        /// </summary>
        internal static string Trace_MaximumZ {
            get {
                return ResourceManager.GetString("Trace_MaximumZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value of X.
        /// </summary>
        internal static string Trace_MinimumX {
            get {
                return ResourceManager.GetString("Trace_MinimumX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value of Y.
        /// </summary>
        internal static string Trace_MinimumY {
            get {
                return ResourceManager.GetString("Trace_MinimumY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value of Z.
        /// </summary>
        internal static string Trace_MinimumZ {
            get {
                return ResourceManager.GetString("Trace_MinimumZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X component of orientation.
        /// </summary>
        internal static string Trace_OrientationX {
            get {
                return ResourceManager.GetString("Trace_OrientationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y component of orientation.
        /// </summary>
        internal static string Trace_OrientationY {
            get {
                return ResourceManager.GetString("Trace_OrientationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Z component of orientation.
        /// </summary>
        internal static string Trace_OrientationZ {
            get {
                return ResourceManager.GetString("Trace_OrientationZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The texture of the trace.
        /// </summary>
        internal static string Trace_Pattern {
            get {
                return ResourceManager.GetString("Trace_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X component of scale.
        /// </summary>
        internal static string Trace_ScaleX {
            get {
                return ResourceManager.GetString("Trace_ScaleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y component of scale.
        /// </summary>
        internal static string Trace_ScaleY {
            get {
                return ResourceManager.GetString("Trace_ScaleY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Z component of scale.
        /// </summary>
        internal static string Trace_ScaleZ {
            get {
                return ResourceManager.GetString("Trace_ScaleZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float
        ///  t = timeValue,
        ///  x = position.x,
        ///  y = position.y,
        ///  z = position.z,
        ///  r = 0,
        ///  g = 0,
        ///  b = 0;
        ///
        ///z = sqrt(x * x + y * y);
        ///z = cos(20 * z - 10 * t) * exp(-3 * z);
        ///r = (x + 1) / 2;
        ///g = (y + 1) / 2;
        ///b = clamp(abs(5 * z), 0, 1);
        ///
        ///gl_Position = projection * cameraView * transform * vec4(x, y, z, 1);
        ///colour = vec3(r, g, b);.
        /// </summary>
        internal static string Trace_Shader1Vertex {
            get {
                return ResourceManager.GetString("Trace_Shader1Vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Trace_Shader2TessControl {
            get {
                return ResourceManager.GetString("Trace_Shader2TessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Trace_Shader3TessEvaluation {
            get {
                return ResourceManager.GetString("Trace_Shader3TessEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Trace_Shader4Geometry {
            get {
                return ResourceManager.GetString("Trace_Shader4Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FragColor = vec4(colour, 0.1);.
        /// </summary>
        internal static string Trace_Shader5Fragment {
            get {
                return ResourceManager.GetString("Trace_Shader5Fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Trace_Shader6Compute {
            get {
                return ResourceManager.GetString("Trace_Shader6Compute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of strips in the X direction.
        /// </summary>
        internal static string Trace_StripCountX {
            get {
                return ResourceManager.GetString("Trace_StripCountX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of strips in the Y direction.
        /// </summary>
        internal static string Trace_StripCountY {
            get {
                return ResourceManager.GetString("Trace_StripCountY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of strips in the Z direction.
        /// </summary>
        internal static string Trace_StripCountZ {
            get {
                return ResourceManager.GetString("Trace_StripCountZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not this trace is visible.
        /// </summary>
        internal static string Trace_Visible {
            get {
                return ResourceManager.GetString("Trace_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebInsertHyperlinkHS {
            get {
                object obj = ResourceManager.GetObject("WebInsertHyperlinkHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZoomHS {
            get {
                object obj = ResourceManager.GetObject("ZoomHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
